/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;


import jmarketmysql.FabricaDeEntidades;
import controller.ClienteJpaController;
import controller.FornecedorJpaController;
import controller.ProdutoJpaController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Br
 */
public class ViewPrincipal extends javax.swing.JFrame {

    private ClienteJpaController clienteJpaController = new ClienteJpaController(FabricaDeEntidades.getInstance().getEntityManagerFactory());
    private ProdutoJpaController produtoJpaController = new ProdutoJpaController(FabricaDeEntidades.getInstance().getEntityManagerFactory());
    private FornecedorJpaController fornecedorJpaController = new FornecedorJpaController(FabricaDeEntidades.getInstance().getEntityManagerFactory());
    
    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        uJPanelImagem1 = new componentes.UJPanelImagem();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        btClientes = new javax.swing.JButton();
        btProdutos = new javax.swing.JButton();
        btFornecedores = new javax.swing.JButton();
        btUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btRegistrarVenda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btRelCliente = new javax.swing.JButton();
        btRelFornecedor = new javax.swing.JButton();
        btRelProduto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mnuSair = new javax.swing.JMenuItem();
        jmCadastrar = new javax.swing.JMenu();
        jmiClientes = new javax.swing.JMenuItem();
        jmiProdutos = new javax.swing.JMenuItem();
        jmiFornecedor = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmVendas = new javax.swing.JMenu();
        mnuRegistrarVenda = new javax.swing.JMenuItem();
        jmiConsultarVenda = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiRelClientes = new javax.swing.JMenuItem();
        jmiRelFornecedor = new javax.swing.JMenuItem();
        jmiRelProdutos = new javax.swing.JMenuItem();
        jmAjuda = new javax.swing.JMenu();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("jMenu4");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JMarket");

        uJPanelImagem1.setImagem(new java.io.File("C:\\BLVendasMySQL\\src\\imagens\\parede-fundo-azul.jpg"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu rápido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N
        jToolBar1.setForeground(new java.awt.Color(102, 102, 102));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Cadastro");
        jToolBar1.add(jLabel1);

        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/User group.png"))); // NOI18N
        btClientes.setText("Clientes");
        btClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btClientes.setMaximumSize(new java.awt.Dimension(200, 40));
        btClientes.setMinimumSize(new java.awt.Dimension(200, 40));
        btClientes.setPreferredSize(new java.awt.Dimension(200, 40));
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btClientes);

        btProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Component.png"))); // NOI18N
        btProdutos.setText("Produtos");
        btProdutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btProdutos.setMaximumSize(new java.awt.Dimension(200, 40));
        btProdutos.setMinimumSize(new java.awt.Dimension(200, 40));
        btProdutos.setPreferredSize(new java.awt.Dimension(200, 40));
        btProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(btProdutos);

        btFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Boss.png"))); // NOI18N
        btFornecedores.setText("Fornecedor");
        btFornecedores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btFornecedores.setMaximumSize(new java.awt.Dimension(200, 40));
        btFornecedores.setMinimumSize(new java.awt.Dimension(200, 40));
        btFornecedores.setPreferredSize(new java.awt.Dimension(200, 40));
        btFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedoresActionPerformed(evt);
            }
        });
        jToolBar1.add(btFornecedores);

        btUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/People.png"))); // NOI18N
        btUsuario.setText("Usuário");
        btUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btUsuario.setMaximumSize(new java.awt.Dimension(200, 40));
        btUsuario.setMinimumSize(new java.awt.Dimension(200, 40));
        btUsuario.setPreferredSize(new java.awt.Dimension(200, 40));
        btUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(btUsuario);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Saida");
        jToolBar1.add(jLabel2);

        btRegistrarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Shopping cart.png"))); // NOI18N
        btRegistrarVenda.setText("Registrar Venda");
        btRegistrarVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btRegistrarVenda.setMaximumSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda.setMinimumSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda.setPreferredSize(new java.awt.Dimension(200, 40));
        btRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarVendaActionPerformed(evt);
            }
        });
        jToolBar1.add(btRegistrarVenda);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Relatórios");
        jToolBar1.add(jLabel3);

        btRelCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Report.png"))); // NOI18N
        btRelCliente.setText("Relatório de clientes");
        btRelCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btRelCliente.setFocusable(false);
        btRelCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btRelCliente.setMaximumSize(new java.awt.Dimension(200, 40));
        btRelCliente.setMinimumSize(new java.awt.Dimension(200, 40));
        btRelCliente.setPreferredSize(new java.awt.Dimension(200, 40));
        btRelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(btRelCliente);

        btRelFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Report.png"))); // NOI18N
        btRelFornecedor.setText("Relatório de fornecedores");
        btRelFornecedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btRelFornecedor.setFocusable(false);
        btRelFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btRelFornecedor.setMaximumSize(new java.awt.Dimension(200, 40));
        btRelFornecedor.setMinimumSize(new java.awt.Dimension(200, 40));
        btRelFornecedor.setPreferredSize(new java.awt.Dimension(200, 40));
        btRelFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelFornecedorActionPerformed(evt);
            }
        });
        jToolBar1.add(btRelFornecedor);

        btRelProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Report.png"))); // NOI18N
        btRelProduto.setText("Relatório de produtos");
        btRelProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btRelProduto.setFocusable(false);
        btRelProduto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btRelProduto.setMaximumSize(new java.awt.Dimension(200, 40));
        btRelProduto.setMinimumSize(new java.awt.Dimension(200, 40));
        btRelProduto.setPreferredSize(new java.awt.Dimension(200, 40));
        btRelProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelProdutoActionPerformed(evt);
            }
        });
        jToolBar1.add(btRelProduto);

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        jmArquivo.setText("Arquivo");

        jmiSobre.setText("Sobre o Sistema...");
        jmiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSobreActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiSobre);
        jmArquivo.add(jSeparator1);

        mnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        jmArquivo.add(mnuSair);

        jMenuBar1.add(jmArquivo);

        jmCadastrar.setText("Cadastros");

        jmiClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jmiClientes.setText("Clientes");
        jmiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiClientes);

        jmiProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jmiProdutos.setText("Produtos");
        jmiProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutosActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiProdutos);

        jmiFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jmiFornecedor.setText("Fornecedores");
        jmiFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedorActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiFornecedor);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmCadastrar.add(jMenuItem1);

        jMenuBar1.add(jmCadastrar);

        jmVendas.setText("Vendas");

        mnuRegistrarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        mnuRegistrarVenda.setText("Vendas");
        mnuRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistrarVendaActionPerformed(evt);
            }
        });
        jmVendas.add(mnuRegistrarVenda);

        jmiConsultarVenda.setText("Consultar vendas");
        jmiConsultarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarVendaActionPerformed(evt);
            }
        });
        jmVendas.add(jmiConsultarVenda);

        jMenuBar1.add(jmVendas);

        jMenu1.setText("Relatórios");

        jmiRelClientes.setText("Clientes");
        jmiRelClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelClientes);

        jmiRelFornecedor.setText("Fornecedores");
        jmiRelFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelFornecedor);

        jmiRelProdutos.setText("Produtos");
        jmiRelProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelProdutos);

        jMenuBar1.add(jMenu1);

        jmAjuda.setText("Ajuda");
        jMenuBar1.add(jmAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreActionPerformed
        JOptionPane.showMessageDialog(null, "www.blsoft.com.br");
    }//GEN-LAST:event_jmiSobreActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSairActionPerformed

    private void jmiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesActionPerformed
        new ViewClientes().setVisible(true);
    }//GEN-LAST:event_jmiClientesActionPerformed

    private void jmiProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutosActionPerformed
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_jmiProdutosActionPerformed

    private void jmiFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedorActionPerformed
        new ViewFornecedor().setVisible(true);
    }//GEN-LAST:event_jmiFornecedorActionPerformed

    private void mnuRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistrarVendaActionPerformed
        new ViewVenda().setVisible(true);
    }//GEN-LAST:event_mnuRegistrarVendaActionPerformed

    private void jmiConsultarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarVendaActionPerformed
        ViewVenda venda = new ViewVenda();
        venda.setViewConsultarVendas();
        venda.setVisible(true);
    }//GEN-LAST:event_jmiConsultarVendaActionPerformed

    private void jmiRelClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelClientesActionPerformed
        // imprimir clientes
        this.clienteJpaController.gerarRelatorioCliente();
    }//GEN-LAST:event_jmiRelClientesActionPerformed

    private void jmiRelFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelFornecedorActionPerformed
        // imrimir fornecedores
        this.fornecedorJpaController.gerarRelatorioFornecedor();
    }//GEN-LAST:event_jmiRelFornecedorActionPerformed

    private void jmiRelProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelProdutosActionPerformed
        // imprimir produtos
        this.produtoJpaController.gerarRelatorioProduto();
    }//GEN-LAST:event_jmiRelProdutosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarVendaActionPerformed
        new ViewVenda().setVisible(true);
    }//GEN-LAST:event_btRegistrarVendaActionPerformed

    private void btUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioActionPerformed
        // TODO add your handling code here:
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_btUsuarioActionPerformed

    private void btFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedoresActionPerformed
        new ViewFornecedor().setVisible(true);
    }//GEN-LAST:event_btFornecedoresActionPerformed

    private void btProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutosActionPerformed
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_btProdutosActionPerformed

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        new ViewClientes().setVisible(true);
    }//GEN-LAST:event_btClientesActionPerformed

    private void btRelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelClienteActionPerformed
        // imprimir clientes
        this.clienteJpaController.gerarRelatorioCliente();
    }//GEN-LAST:event_btRelClienteActionPerformed

    private void btRelFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelFornecedorActionPerformed
        // imrimir fornecedores
        this.fornecedorJpaController.gerarRelatorioFornecedor();
    }//GEN-LAST:event_btRelFornecedorActionPerformed

    private void btRelProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelProdutoActionPerformed
        // imrimir fornecedores
        this.produtoJpaController.gerarRelatorioProduto();
    }//GEN-LAST:event_btRelProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btFornecedores;
    private javax.swing.JButton btProdutos;
    private javax.swing.JButton btRegistrarVenda;
    private javax.swing.JButton btRelCliente;
    private javax.swing.JButton btRelFornecedor;
    private javax.swing.JButton btRelProduto;
    private javax.swing.JButton btUsuario;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenu jmVendas;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiConsultarVenda;
    private javax.swing.JMenuItem jmiFornecedor;
    private javax.swing.JMenuItem jmiProdutos;
    private javax.swing.JMenuItem jmiRelClientes;
    private javax.swing.JMenuItem jmiRelFornecedor;
    private javax.swing.JMenuItem jmiRelProdutos;
    private javax.swing.JMenuItem jmiSobre;
    private javax.swing.JMenuItem mnuRegistrarVenda;
    private javax.swing.JMenuItem mnuSair;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables
}
